# Generated by Django 3.1.2 on 2020-10-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20201026_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
