# Generated by Django 3.1.2 on 2020-10-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20201026_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('prepping', 'prepping'), ('in progress', 'in progress'), ('drafted', 'drafted'), ('completed', 'completed'), ('published', 'published')], default='PR', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('novel', 'novel'), ('short story', 'short story'), ('memoir', 'memoir'), ('script', 'script'), ('nonfiction', 'nonfiction'), ('poetry', 'poetry'), ('other', 'other')], default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.CharField(choices=[('words', 'words'), ('characters', 'characters'), ('pages', 'pages'), ('minutes', 'minutes'), ('hours', 'hours'), ('other', 'other')], default='W', max_length=20),
        ),
    ]
