# Generated by Django 3.2.7 on 2021-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20201101_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('prepping', 'prepping'), ('in progress', 'in progress'), ('drafted', 'drafted'), ('completed', 'completed'), ('published', 'published')], default='prepping', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('novel', 'novel'), ('short story', 'short story'), ('memoir', 'memoir'), ('script', 'script'), ('nonfiction', 'nonfiction'), ('poetry', 'poetry'), ('other', 'other')], default='novel', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.CharField(choices=[('words', 'words'), ('characters', 'characters'), ('pages', 'pages'), ('minutes', 'minutes'), ('hours', 'hours'), ('other', 'other')], default='words', max_length=20),
        ),
    ]
