# Generated by Django 3.2.7 on 2021-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_auto_20210929_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='excerpt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='pinterest',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='spotify',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='synopsis',
            field=models.TextField(default=''),
        ),
    ]
