# Generated by Django 3.2.7 on 2021-09-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_auto_20210929_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='excerpt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pinterest',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='spotify',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='synopsis',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
