# Generated by Django 3.2.7 on 2021-10-07 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_auto_20210929_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 7, 6, 44, 11, 858295, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 7, 6, 44, 11, 895221, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 6, 44, 11, 895847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
