# Generated by Django 3.2.7 on 2021-10-15 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_auto_20211015_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 15, 12, 16, 45, 867854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 15, 12, 16, 45, 908918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 12, 16, 45, 909797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 15, 12, 16, 45, 909875, tzinfo=utc), null=True),
        ),
    ]
