# Generated by Django 3.2.7 on 2021-10-15 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_auto_20211015_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 15, 12, 38, 33, 235010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 15, 12, 38, 33, 278634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 12, 38, 33, 279537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 15, 12, 38, 33, 279610, tzinfo=utc), null=True),
        ),
    ]
