# Generated by Django 3.2.7 on 2021-11-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_auto_20211101_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
