# Generated by Django 3.2.7 on 2021-11-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0019_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='#6f42c1', max_length=7, null=True),
        ),
    ]
