# Generated by Django 3.2.7 on 2021-11-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0020_alter_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(1, '1 - high priority'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - default'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - low priority')], default=5),
        ),
    ]
