# Generated by Django 3.2.7 on 2021-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0022_auto_20211103_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goodreads',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nanowrimo',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinterest',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
