# Generated by Django 3.2.7 on 2021-11-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0023_auto_20211103_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wattpad',
            field=models.URLField(blank=True, default='', help_text='insert your wattpad profile URL', null=True, verbose_name='Wattpad'),
        ),
        migrations.AlterField(
            model_name='log',
            name='count',
            field=models.IntegerField(help_text='what is your progress?', verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default='', help_text='insert the date of your log (YYYY-MM-DD)', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='log',
            name='note',
            field=models.TextField(blank=True, help_text='do you want to comment your log?', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='log',
            name='project',
            field=models.ForeignKey(help_text='for which project do you want to save a log?', on_delete=django.db.models.deletion.CASCADE, to='logs.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default='', help_text='give your log a time (HH:MM:SS)', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, default='', help_text='Tell us something about yourself!', null=True, verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.CharField(blank=True, default='#5a5c69', help_text='select a color to be used in your profile page', max_length=7, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_goal',
            field=models.IntegerField(blank=True, help_text='set a daily goal you want to reach', null=True, verbose_name='Daily Goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_unit',
            field=models.CharField(blank=True, choices=[('words', 'words'), ('characters', 'characters'), ('pages', 'pages'), ('minutes', 'minutes'), ('hours', 'hours'), ('other', 'other')], default='words', help_text='in which unit do you want to measure your daily goal?', max_length=20, null=True, verbose_name='Goal Unit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goodreads',
            field=models.URLField(blank=True, default='', help_text='insert your goodreads profile URL', null=True, verbose_name='Goodreads'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=models.ImageField(blank=True, default=None, help_text='select a header image for your profile page', null=True, upload_to='images', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, default='', help_text='insert your instagram profile URL', null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Others can then see your Profile page as you can see it.', verbose_name='Should your profile be visible for others?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nanowrimo',
            field=models.URLField(blank=True, default='', help_text='insert your nanowrimo.org profile URL', null=True, verbose_name='NaNoWriMo.org'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pinterest',
            field=models.URLField(blank=True, default='', help_text='insert your pinterest profile URL', null=True, verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, help_text='select an image to display yourself', null=True, upload_to='images', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify',
            field=models.URLField(blank=True, default='', help_text='insert your spotify profile URL', null=True, verbose_name='Spotify'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, default='', help_text='insert your twitter profile URL', null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='#6f42c1', help_text='select a color (please use hexadecimal html codation, e.g. #00ff00)', max_length=7, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, default='', help_text='do you have a deadline? (YYYY-MM-DD)', null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='give an example of your work', null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=50000, help_text='which goal do you want to reach?', verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='give your project cover image', null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Other users then can see cover, description texts and links', verbose_name='Should your project be visible to other users?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pinterest',
            field=models.URLField(blank=True, default='', help_text='insert URL of pinterest board', null=True, verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(1, '1 - high priority'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - default'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - low priority')], default=5, help_text='which priority does your project have?', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='project',
            name='spotify',
            field=models.URLField(blank=True, default='', help_text='insert URL of spotify playlist', null=True, verbose_name='Spotify'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('prepping', 'prepping'), ('in progress', 'in progress'), ('drafted', 'drafted'), ('completed', 'completed'), ('published', 'published')], default='prepping', help_text='what is the status of your project?', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='does your project has a subtitle?', max_length=300, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='project',
            name='synopsis',
            field=models.TextField(blank=True, default='', help_text='what is your project about?', null=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', help_text='give your project a name', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.CharField(blank=True, default='', help_text='write things like genre, tags, ...', max_length=200, null=True, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('novel', 'novel'), ('short story', 'short story'), ('memoir', 'memoir'), ('script', 'script'), ('nonfiction', 'nonfiction'), ('poetry', 'poetry'), ('other', 'other')], default='novel', help_text='what kind of project is your project?', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.CharField(choices=[('words', 'words'), ('characters', 'characters'), ('pages', 'pages'), ('minutes', 'minutes'), ('hours', 'hours'), ('other', 'other')], default='words', help_text='in which unit do you want to measure your progress?', max_length=20, verbose_name='Unit'),
        ),
    ]
